export enum EstadosPedidos {
  PENDIENTE = 'PENDIENTE',
  EN_AUTORIZACION = 'EN AUTORIZACION',
  EN_PREPARACION = 'EN PREPARACION',
  EN_EMPAQUETADO = 'EN EMPAQUETADO',
  EN_DESPACHO = 'EN DESPACHO',
  EN_DISTRIBUCION = 'EN DISTRIBUCION',
  EN_FACTURACION = 'EN FACTURACION',
  COMPLETADO = 'COMPLETADO',
  CANCELADO = 'CANCELADO'
}